### ISSUE TITLE
Hoàn thiện đồ án cuối kỳ Lập trình cho Khoa học dữ liệu

### ISSUE THREAD

**Issue by vohieu00** [viplazylmht/P4DS_final#20]
Thân gửi quý thầy cô và các bạn,

Hiện tại nhóm đã thực hiện xong đồ án cuối kỳ cho môn học với đề tài về y tế ở bang New York năm 2015. Trong quá trình làm việc không tránh khỏi những thiếu sót, mời thầy và các bạn đóng góp ý kiến.

Thân,
Nhóm 20

**Comment by TrNgTinh** [comment]
Nhóm 19 - Trần Ngọc Tịnh - 18120597
Ưu điểm:

1. Trình bày tệp tin notebook có các thư mục rõ ràng để tiện theo dõi.
2. Các câu hỏi đưa ra có ý nghĩa, không những trả lời mà còn đưa ra các giải pháp cho vấn đề.
3. Bộ dữ liệu có khá nhiều thuộc tính.

Góp ý:

1. Phần điền dữ liệu khuyết nên bổ sung markdown để người đọc tiện theo dõi.
2. Mình không chắc là việc sử dụng thư viện `Scipy` và `Seaborn` này đã được thầy chấp nhận chưa.
3. Phần Code của bạn mình thấy có sử dụng khá nhiều hàm và có những dòng code dài dẫn đến việc khó quan sát.

Trên đây là những nhận xét và góp ý của mình, nhìn chung nhóm bạn hoàn thành đồ án khá là công phu :wave:. Chúc nhóm bạn đạt được điểm cao :smile_cat:.

**Comment by MinhTho-162** [comment]
Nhóm 19 - Đặng Minh Thọ - 18120579
Mình xin nhận xét đồ án của nhóm bạn:
Ưu điểm:
- Nhóm bạn trình bày các thư mục rõ ráng
- Đưa ra câu hỏi ý nghĩa, giải thích rõ ràng dễ hiểu, đưa ra giải pháp giải quyết vấn đề hay
- Đề tài rất hay
Góp ý:
- Sử dụng nhiều hàm với những dòng code dài dẫn đến việc khó quan sát
-  Ở phần nhận xét cuối câu 3 'chỉ số cấp cứ' 
-  Ở phần vẽ biểu đồ tròn 'Zip code 142 gender distribution' mình thấy % của U là 0.0%, mình nghĩ là nên xóa cái U đó đi để nhìn gọn hơn
Đây là những nhận xét và góp ý của mình, nhóm bạn hoàn thành đồ án rất tốt Chúc nhóm bạn đạt được điểm cao

**Comment by viplazylmht** [comment]
Hi 2 bạn, đầu tiên mình cảm ơn 2 bạn đã đưa ra những lời nhận xét có cánh về bài làm của nhóm mình.

Mình xin phép trả lời phần góp ý của bạn @MinhTho-162 như sau:

- >Sử dụng nhiều hàm với những dòng code dài dẫn đến việc khó quan sát  

  Theo như máy mình zoom ở chế độ 110% thì chỉ có 2 chỗ code là tràn ra khỏi kích thước của cell thôi. Tất nhiên là mình sẽ sửa lại ở trong commit tới ✌️ 

- >'chỉ số cấp cứ'  

  Hjhj, my bad typo, thank u so much!

- > Ở phần vẽ biểu đồ tròn 'Zip code 142 gender distribution' mình thấy % của U là 0.0%, mình nghĩ là nên xóa cái U đó đi để nhìn gọn hơn

  Chắc là bạn đang đề cập đến hình này:
 
  ![image](https://user-images.githubusercontent.com/20496271/125169029-925ecc00-e1d2-11eb-843f-9a7ca6c5b041.png)

  Thực ra không nói thì mình cũng không để ý, U chỉ là Unknown thôi chứ hóa ra không phải giới tính khác. Mình sẽ sửa lại chỗ này để đảm bảo nhất quán dữ liệu.

Vậy đó, mình xin cảm ơn những góp ý của các bạn và chúc nhóm các bạn cũng sẽ đạt được kết quả như mong đợi.  🥇

**Comment by vohieu00** [comment]
> Nhóm 19 - Trần Ngọc Tịnh - 18120597
> Ưu điểm:
> 
> 1. Trình bày tệp tin notebook có các thư mục rõ ràng để tiện theo dõi.
> 2. Các câu hỏi đưa ra có ý nghĩa, không những trả lời mà còn đưa ra các giải pháp cho vấn đề.
> 3. Bộ dữ liệu có khá nhiều thuộc tính.
> 
> Góp ý:
> 
> 1. Phần điền dữ liệu khuyết nên bổ sung markdown để người đọc tiện theo dõi.
> 2. Mình không chắc là việc sử dụng thư viện `Scipy` và `Seaborn` này đã được thầy chấp nhận chưa.
> 3. Phần Code của bạn mình thấy có sử dụng khá nhiều hàm và có những dòng code dài dẫn đến việc khó quan sát.
> 
> Trên đây là những nhận xét và góp ý của mình, nhìn chung nhóm bạn hoàn thành đồ án khá là công phu . Chúc nhóm bạn đạt được điểm cao .

Hi bạn,
Cảm ơn bạn đã dành thời gian cho nhóm mình cũng như những đóng góp của bạn. Việc sử dụng thêm thư viện mình đã có xin ý kiến của thầy và thầy cũng đã cho phương án phù hợp bạn nhé. Phần code hơi dài vì mình muốn hạn chế tạo thêm biến mới và muốn mỗi câu lệnh có một chức năng riêng biệt rõ ràng hơn thôi, mình sẽ cố gắng xem lại cả phần này và bổ sung markdown. Một lần nữa, cảm ơn bạn ^^
Hiếu
